### ISSUE TITLE
Input file causes total time to be: ( -30:-8)

### ISSUE THREAD

**Issue by eyal0** [arhi/gcodestat#7]
The command that I run from latest sources:

`./gcodestat.exe -c samples/config.txt -g ~/Downloads/DINOSAUR_JUMP.gco`

Output:

```
gcodestat v0.9
Starting with parameters:
        acceleration:           1000.000000 mm/sec/sec
        junction deviation:     0.020000
        x max speed:            30000.000000 mm/min
        y max speed:            30000.000000 mm/min
        z max speed:            1200.000000 mm/min
        retraction time:        0.000000 sec
        prime time:             0.000000 sec
        speed override:         1.000000
        absolute movement:      yes
        absolute extrusion:     yes
        metering unit:          mm

Total time: ( -30:-8 )

```
[dino_jump.zip](https://github.com/arhi/gcodestat/files/2135956/dino_jump.zip)

**Comment by arhi** [comment]
interesting bug, if you do a move before setting any feed rate printer will use default feed rate and in my case that's 0 so infinite amount of time required for moves before the first F is introduced... fixed by adding default feed rate to a hardcoded value.. will read that from config in one of future versions :)

thanks for the report!
